services:
  data-generator:
    build:
      context: ./data-generator
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./data-generator:/app
    ports:
      - '3001:3001'
    command: npm run start:dev

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./gateway:/app
    ports:
      - '3000:3000'
    command: npm run start:dev

  messageQueue:
    image: rabbitmq:alpine
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - '5672:5672'
  
  events-processor-worker:
    build:
      context: ./events-processor-worker
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./events-processor-worker:/app
    command: go run .

volumes:
  rabbitmq_data:
    driver: local

networks:
  default:
    driver: bridge
